---
title: "Programa de Prevención & Control del Dengue | 2025"
format: 
  dashboard:
      nav-buttons: [twitter, github, facebook]
theme: custom.scss
---

```{r setup_12_guerrero}
library(sf)
mapview::mapviewOptions(default = TRUE,
                        basemaps.color.shuffle = FALSE)
if(as.vector(Sys.info()["sysname"]) == "Darwin"){
load("/Users/fdzul/Documents/geocoding_mx/2025/8.RData/denmex_2025.RData")
} else if(as.vector(Sys.info()["sysname"]) == "Windows"){
   load("D:\\OneDrive\\proyects\\geocoding_mex\\2024\\8.RData\\denmex_2024.RData")
} else if(as.vector(Sys.info()["sysname"]) == "Linux"){
    load("/home/fdzul/Documents/active_transmission/geocoding_mx/8.RData/denmex_2025.RData")
}
library(magrittr)
```


# [**Cadenas de Transmisión**]{style="font-size:8pt"}

::: panel-tabset
### [**Acapulco**]{style="color:#990000"}

```{r chains_acapulco}
denhotspots::transmission_chains_map(geocoded_dataset = z,
                                     cve_edo = "12",
                                     locality = "Acapulco de Juarez",
                                     dengue_cases = "Confirmado")

```


### [**Chilpancingo**]{style="color:#990000"}

```{r chains_chilpo}
denhotspots::transmission_chains_map(geocoded_dataset = z,
                                     cve_edo = "12",
                                     locality = "Chilpancingo de los Bravo",
                                     dengue_cases = "Confirmado")

```


:::


# [**Mapas de Calor**]{style="font-size:8pt"}

::: panel-tabset

### [**Acapulco**]{style="color:#990000"}

```{r}
densnv::mp_heatmap(geocoded_dataset = z,
                   cve_edo = "12",
                   locality = "Acapulco de Juarez",
                   status_caso = c(1, 2),
                   kernel =200,
                   week = c(1:53),
                   zoom = NULL,
                   map_type = NULL,
                   alpha = 0.6,
                   static = FALSE,
                    save = FALSE,
                   palette = viridis::turbo)
```


### [**Chilpancingo**]{style="color:#990000"}

```{r}
densnv::mp_heatmap(geocoded_dataset = z,
                   cve_edo = "12",
                   locality = "Chilpancingo de los Bravo",
                   status_caso = c(1, 2),
                   kernel = 600,
                   week = c(1:53),
                   zoom = NULL,
                   map_type = NULL,
                   alpha = 0.6,
                   static = FALSE,
                    save = FALSE,
                   palette = viridis::turbo)
```


:::

